apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sre-app
  namespace: sre
spec:
  project: default
  source:
    repoURL: https://github.com/ksai7991/SRE-project.git
    path: CD-Python-App-main
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: sre
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
