apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: python-app-monitor
  labels:
    release: monitoring  # Make sure this matches your Prometheus release name
spec:
  selector:
    matchLabels:
      app: python-app
  endpoints:
  - port: http
    path: /metrics
    interval: 15s
