apiVersion: v1
kind: Service
metadata:
  name: python-app-service
  namespace: default  # <-- Add this if not set elsewhere
  labels:
    app: python-app   # <-- Add this to match ServiceMonitor
  annotations:
    prometheus.io/port: "http"
    prometheus.io/scrape: "true"
spec:
  selector:
    app: python-app    # <-- Must match pod label (NOT matchLabels)
  ports:
    - protocol: TCP
      name: http       # <-- Required for Prometheus to match
      port: 80         # Kubernetes service port
      targetPort: 8000 # Pod's container port
  type: NodePort
