apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: python-app-monitor
  labels:
    release: prometheus  # Make sure this matches your Prometheus release name
spec:
  selector:
    matchLabels:
      app: python-app
  namespaceSelector:
    matchNames:
      - default  # or your app's namespace
  endpoints:
  - port: http
    path: /metrics
    interval: 15s
