apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: python-app-monitor
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: python-app
  namespaceSelector:
    matchNames:
      - sre   # 👈 Add this to target services in 'sre' namespace
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
