apiVersion: v1
kind: Service
metadata:
  name: python-app-service
  annotations:
    prometheus.io/port: "http"
    prometheus.io/scrape: "true"
spec:
  selector:
    app: python-app
  ports:
    - protocol: TCP
      name: http
      port: 80  # Internal Kubernetes port
      targetPort: 8000 # Port exposed by the container
  type: NodePort
