prometheus:
  prometheusSpec:
    serviceMonitorSelector: 
      matchLabels:
        release: prometheus
    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitorNamespaceSelector: {}  # Optional: detects monitors from all namespaces
    additionalScrapeConfigs:
      - job_name: 'postgres-exporter-droplet'
        metrics_path: /metrics
        static_configs:
          - targets: ['167.71.177.93:9187']

      - job_name: 'node-exporter-droplet'
        metrics_path: /metrics
        static_configs:
          - targets: ['167.71.177.93:9200']

