{
 "title": "Web App Monitoring",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "job", "query": { "query": "label_values(job)" } }
  ]
 },
 "panels": [
  { "title": "Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Process Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  (time() - process_start_time_seconds{job=\"python-app-service\"})\n  * on(instance) group_left()\n    up{job=\"python-app-service\"}\n)\n> 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_requests_total{job=\"$job\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  (sum(increase(http_requests_total{job=\"$job\", status=~\"4xx\"}[$__range])) or vector(0)) +\n  (sum(increase(http_requests_total{job=\"$job\", status=~\"5xx\"}[$__range])) or vector(0))\n)\n/\n(sum(increase(http_requests_total{job=\"$job\"}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Request Duration",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_sum{ job=\"$job\"}[$__range]))/sum(rate(http_request_duration_seconds_count{ job=\"$job\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API Throughput",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(http_requests_total{job=\"$job\"}[5m])",
     "legendFormat": "{{method}} {{handler}} {{status}}"
    }
   ]
  },
  { "title": "Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Requests by Status Code",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{job=\"$job\"}[$__range])) by (status)",
     "legendFormat": "Status {{status}}"
    }
   ]
  },
  {
   "title": "Request Rate by Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 11 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{job=\"$job\"}[1m]) ) by (status)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Duration", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Average Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "(rate(http_request_duration_seconds_sum{ job=\"$job\"}[1m]))/(rate(http_request_duration_seconds_count{ job=\"$job\"}[1m]))",
     "legendFormat": "{{method}} {{handler}}"
    }
   ]
  },
  {
   "title": "API latency Percentile",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "histogram_quantile(0.4,sum(rate(http_request_duration_seconds_bucket{job=\"$job\"}[5m])) by (le))",
     "legendFormat": "p40"
    },
    {
     "expr": "histogram_quantile(0.95,sum(rate(http_request_duration_seconds_bucket{job=\"$job\"}[5m])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99,sum(rate(http_request_duration_seconds_bucket{job=\"$job\"}[5m])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.9,sum(rate(http_request_duration_seconds_bucket{job=\"$job\"}[5m])) by (le))",
     "legendFormat": "p90"
    }
   ]
  }
 ]
}